### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by thecodeduchess** [ashaney/jammming-master-repo#6]
**Grade:**  Exceeds Expectations

**Summary:**  That is a professional level document! 

No grammatical errors found and you were concise about the implementation of the feature
I like that you suggesting something that has a lot of documentation on the web as well. You gave the links to where to find help with the feature. 

I might have wanted to see some sample code  just to see where your thoughts are and how you might get started on it, (even if it doesn't function) but that's not a big deal. Your technical explanation in English was very detailed. I also love the visual cues! 

Re: caveats, I think you made a fair point there. It would be great to be able to add however many suggestions up to twenty but we have to make sure not to crash the app with non-integer numbers. I like how the user would be able to choose their number and not get too overwhelmed with all the choices rather than whatever a developer decides.

**Comment by ashaney** [comment]
Thank you for the feedback! I enjoyed the content and challenging nature of this course and I'm looking forward to taking more courses in the future.
